const assert=require('node:assert/strict');const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('./node_modules/playwright');

const root=path.resolve('.'),out=path.resolve('tests/results');
const stub=`(()=>{
 window.__calls=[];window.__channels=[];window.__failed=false;
 const user={id:'audit-user',email:'audit@example.invalid',full_name:'حساب فحص محلي',role:'manager',department:'computer-lab',linked_instructors:['محاضر تجريبي'],permissions:{can_approve:true,can_manage_users:true,can_delete:true}};
 window.__profile=user;
 const base={id:'1',instructor:'محاضر تجريبي',course_name:'إدارة سلاسل الإمداد',course_code:'CITL101',room_name:'H 104',day_of_week:'Monday',time_slot:'08:30 - 10:20',status:'active',period_order:1};
 window.__data={profiles:[user],academic_schedule:[base,{...base,id:'2',time_slot:'10:30 - 12:20',period_order:2}],site_settings:[{setting_key:'tv_display_config',setting_value:{activeRooms:['H 104'],slideDurationSeconds:120,examsEnabled:true}},{setting_key:'news_config',setting_value:{text:'أخبار عامة للفحص',sliderVal:50}},{setting_key:'exam_news_config',setting_value:{text:'تعليمات امتحانات للفحص',sliderVal:50}}],rooms:[{id:'room-1',name:'قاعة الاجتماعات',is_active:true}],settings:[{id:1,start_hour:8,end_hour:18}],faculty_directory:[],faculty_directory_public:[],meetings:[],exam_schedule:[],tv_posters:[],attendance_scans:[],page_visits:[]};
 function query(table){let filters=[],single=false,write=false,range=null;const q={};
 for(const m of ['select','eq','neq','in','gte','lte','gt','lt','order','limit','range','single','maybeSingle','insert','update','upsert','delete','is','not','or','ilike'])q[m]=(...a)=>{if(['single','maybeSingle'].includes(m))single=true;if(['eq','in','gte','lte','neq'].includes(m))filters.push([m,...a]);if(m==='range')range=a;if(['insert','update','upsert','delete'].includes(m))write=true;return q};
 q.then=(resolve,reject)=>{window.__calls.push({table,filters,write});if(write)return Promise.resolve({data:null,error:{message:'AUDIT: mutation intercepted'}}).then(resolve,reject);if(window.__failed)return Promise.resolve({data:null,error:{message:'AUDIT: network unavailable'}}).then(resolve,reject);let d=[...(window.__data[table]||[])];for(const [m,k,v]of filters){if(m==='eq')d=d.filter(r=>r[k]===v);if(m==='in')d=d.filter(r=>v.includes(r[k]))}if(range)d=d.slice(range[0],range[1]+1);return Promise.resolve({data:single?(d[0]||null):d,error:null,count:d.length}).then(resolve,reject)};return q}
 const client={from:query,rpc:async(name,args)=>{window.__calls.push({rpc:name,args});if(window.__failed)return {data:null,error:{message:'TEST offline'}};if(name==='citl_effective_schedule')return {data:window.__data.academic_schedule.map(x=>({...x,occurrence_date:'2026-09-07',original_room:x.room_name,original_instructor:x.instructor})),error:null};if(name==='citl_room_names')return{data:['H 104','H 108'],error:null};if(name==='citl_attendance_counts')return{data:{present:0,pending:0},error:null};if(name==='citl_booking_hours')return{data:{start_hour:8,end_hour:18},error:null};return {data:name==='citl_secure_api'?{ok:true,notifications:[],terms:[{id:'t1',code:'AUDIT',name:'ترم تجريبي',is_active:true,starts_on:'2026-09-01',ends_on:'2026-12-30'}],visitors:[],term_visitors:[],schedule_instructors:[],heads:[],rooms:[],qr_eligible_rooms:[],profiles:[user]}:{ok:true,ignored:true},error:null}},channel:(name)=>{const c={on:(event,filter,fn)=>{window.__channels.push({name,event,filter});return c},subscribe:()=>c,unsubscribe:()=>{}};return c},removeChannel:()=>{},auth:{getSession:async()=>({data:{session:window.__anonymous?null:{user}},error:null}),getUser:async()=>({data:{user},error:null}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}}),signOut:async()=>({error:null})},storage:{from:()=>({getPublicUrl:()=>({data:{publicUrl:''}})})}};
 window.supabase={createClient:()=>client};localStorage.setItem('currentUser',JSON.stringify(user));
})();`;
(async()=>{
 const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(p.endsWith(path.sep))p+='index.html';try{const b=fs.readFileSync(p);res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.mp3':'audio/mpeg'})[path.extname(p)]||'text/plain');res.end(b)}catch{res.statusCode=404;res.end('missing')}}).listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));
 const url='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({headless:true,executablePath:process.env.CITL_CHROMIUM_PATH||undefined,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1920,height:1080},timezoneId:'Africa/Cairo',serviceWorkers:'block'});
 await context.route('**/*',async route=>{const u=route.request().url();if(u.includes('/vendor/supabase-js'))return route.fulfill({contentType:'application/javascript',body:stub});if(u.includes('email.min.js'))return route.fulfill({contentType:'application/javascript',body:'window.emailjs={init(){},send(){return Promise.resolve()}}'});if(!u.startsWith(url))return route.abort();return route.continue()});
 const page=await context.newPage();await page.clock.setFixedTime(new Date('2026-09-07T06:00:00Z'));const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const results={externalNetwork:'blocked; Supabase mocked; no production reads/writes',checks:[]};
 await page.goto(url+'/tv_display/');await page.waitForTimeout(700);
 results.checks.push({name:'TV initial normal fixture',state:await page.evaluate(()=>({mode:isExamMode,rooms:displayRooms,rotation:getComputedStyle(document.body).transform,text:document.getElementById('content-container').innerText,ticker:document.getElementById('news-ticker-content').innerText}))});
 
 results.checks.push({name:'Ticker speed-only change',value:await page.evaluate(()=>{applyNewsTickerDOM({text:'اختبار سرعة',sliderVal:20});const before=document.documentElement.style.getPropertyValue('--ticker-speed');applyNewsTickerDOM({text:'اختبار سرعة',sliderVal:90});return{before,after:document.documentElement.style.getPropertyValue('--ticker-speed')}})});
 results.checks.push({name:'DB errors after successful timetable fetch',value:await page.evaluate(async()=>{window.__failed=true;await fetchData();return{rooms:displayRooms,text:document.getElementById('content-container').innerText,indicator:document.querySelector('footer').innerText.includes('تحديث تلقائي مباشر')}})});
 await page.evaluate(()=>{window.__failed=false;window.__data.site_settings=window.__data.site_settings.filter(x=>x.setting_key!=='tv_display_config')});await page.reload();await page.waitForTimeout(200); // stub resets config; explicitly reset to actual cold path next
 results.checks.push({name:'Fresh install missing settings',value:await page.evaluate(async()=>{localStorage.clear();activeRooms=[];window.__data.site_settings=[];await loadTvDisplayConfig();await fetchData();return{activeRooms,text:document.getElementById('content-container').innerText}})});
 results.checks.push({name:'Room outside hardcoded list',value:await page.evaluate(()=>{applyTvDisplayConfig({activeRooms:['NEW 999'],slideDurationSeconds:10});return activeRooms})});
 await page.evaluate(async()=>{window.__data.exam_schedule=Array.from({length:14},(_,i)=>({id:i+1,exam_date:'2026-09-07',start_time:'09:00:00',end_time:'11:00:00',academic_level:'الثالثة',course_name:'الاقتصاد وإدارة الخدمات اللوجستية الدولية',course_code:'CITL'+i,instructor:'محاضر امتحان تجريبي',room_name:'H '+(104+i),course_language:'A',group_number:1}));await fetchData()});await page.waitForTimeout(700);
 results.checks.push({name:'Exam pagination',value:await page.evaluate(()=>({pages:examPages.map(p=>p.items.length),examRows:examPages.reduce((n,p)=>n+p.items.filter(x=>!x.isDivider).length,0),channels:window.__channels.map(c=>c.filter.table)}))});
 results.checks.push({name:'Ticker untrusted HTML interpreted',value:await page.evaluate(()=>{applyNewsTickerDOM({text:'<b data-audit="inert">اختبار</b>',sliderVal:50});return !!document.querySelector('[data-audit="inert"]')})});
 for(const route of ['/','/schedules/','/dashboard/','/smrm/','/today/','/attendance/','/management/','/404.html']){
 errors.length=0;await page.goto(url+route);await page.waitForTimeout(500);
 if(route==='/schedules/')await page.evaluate(()=>renderResults(window.__data.academic_schedule));
 
 const state=await page.evaluate(()=>({title:document.title,path:location.pathname,overflow:document.documentElement.scrollWidth>innerWidth,calls:window.__calls?.length,mutationsIntercepted:window.__calls?.filter(c=>c.write).length}));results.checks.push({name:'Page local smoke '+route,state,errors:[...errors]});
 if(route==='/dashboard/')results.checks.push({name:'Booking cross-room conflict + time mismatch',value:await page.evaluate(()=>({conflicts:dashCountReservationConflicts([{room_id:'A',start_time:'09:00',end_time:'10:00'},{room_id:'B',start_time:'09:00',end_time:'10:00'}]),implicitEnd:dashScheduleEndMinutes('08:30'),durationOverflow:calculateEndTime('23:00',2)}))});
 }
 const byName=name=>results.checks.find(x=>x.name===name);assert.deepEqual(byName('TV initial normal fixture').state.rooms,['H 104']);assert.equal(byName('TV initial normal fixture').state.rotation,'matrix(0, 1, -1, 0, 0, 0)');assert.equal(byName('DB errors after successful timetable fetch').value.text,byName('TV initial normal fixture').state.text);assert.equal(byName('Exam pagination').value.examRows,14);assert.equal(byName('Ticker untrusted HTML interpreted').value,false);assert.notEqual(byName('Ticker speed-only change').value.before,byName('Ticker speed-only change').value.after);assert.equal(byName('Booking cross-room conflict + time mismatch').value.durationOverflow,'');for(const check of results.checks.filter(x=>x.errors))assert.deepEqual(check.errors,[],check.name);results.assertionsPassed=true;results.tvErrors=[...errors];fs.writeFileSync(out+'/qa-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
