import {PGlite}from './node_modules/@electric-sql/pglite/dist/index.js';import {pgcrypto}from './node_modules/@electric-sql/pglite/dist/contrib/pgcrypto.js';import fs from'node:fs';import assert from'node:assert/strict';
const db=new PGlite({extensions:{pgcrypto}});const results=[];
const admin='00000000-0000-0000-0000-000000000001',user='00000000-0000-0000-0000-000000000002',partial='00000000-0000-0000-0000-000000000003',visitor='00000000-0000-0000-0000-000000000004',head='00000000-0000-0000-0000-000000000005';
async function as(id){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id||'']);if(id)await db.exec('set role authenticated');}
async function q(sql,args=[]){return (await db.query(sql,args)).rows;}
async function value(sql,args=[]){return Object.values((await q(sql,args))[0])[0];}
async function expectFail(fn,pattern){let failed=false;try{await fn();}catch(e){failed=true;if(pattern)assert.match(e.message,pattern);}assert.ok(failed,'Expected rejection');}
async function test(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:e.message,where:e.where});console.log('FAIL',name,e.message,e.where||'');}}
try{
 await db.exec(fs.readFileSync('tests/schema-fixture.sql','utf8'));
 const migration=fs.readFileSync('SUPABASE-REPAIR.sql','utf8');await db.exec(migration);await db.exec(migration);
 for(const [id,name,role,perms]of [[admin,'Admin','manager',{}],[user,'User','user',{}],[partial,'Approver','manager',{can_approve:true,can_manage_users:false,can_delete:false}],[visitor,'Visitor','user',{}],[head,'Head','user',{}]]){
 await q('insert into auth.users(id,email)values($1,$2)',[id,name+'@example.invalid']);await q('insert into profiles(id,email,full_name,role,permissions)values($1,$2,$3,$4,$5)',[id,name+'@example.invalid',name,role,JSON.stringify(perms)]);}
 const room=await value("insert into rooms(name)values('H 104')returning id");const otherRoom=await value("insert into rooms(name)values('H 108')returning id");
 await q('insert into settings values(1,0,23)');
 await test('Canonical timing, explicit end and Arabic digits',async()=>{for(const [v,a,b]of [['08:30','08:30:00','10:20:00'],['02:30','14:30:00','16:20:00'],['08:30 - 09:15','08:30:00','09:15:00'],['٠٢:٣٠ - ٠٤:٢٠','14:30:00','16:20:00'],['02:30 AM - 03:00 AM','02:30:00','03:00:00']])assert.deepEqual(await value('select citl_parse_time_slot($1)',[v]),[a,b]);});
 await test('Partial approver cannot administer users or schedules',async()=>{await as(partial);assert.equal(await value("select is_manager()"),false);assert.equal(await value("select citl_can('can_approve')"),true);await expectFail(()=>q("select citl_secure_api('management.snapshot')"));await expectFail(()=>q("select citl_secure_api('registration.manager_ticket','{}')"));});
 let booking;
 await test('Pending insert allowed, forged approval rejected',async()=>{await as(user);await expectFail(()=>q("insert into meetings(user_id,room_id,title,date,start_time,end_time,status)values($1,$2,'Forged','2026-10-05','10:00','11:00','confirmed')",[user,room]));booking=await value("insert into meetings(user_id,room_id,title,date,start_time,end_time,status)values($1,$2,'Booking','2026-10-05','10:00','11:00','pending')returning id",[user,room]);});
 await test('Approval, adjacency and room separation',async()=>{await as(partial);await q("update meetings set status='confirmed'where id=$1",[booking]);await q("insert into meetings(user_id,room_id,title,date,start_time,end_time,status)values($1,$2,'Other room','2026-10-05','10:00','11:00','confirmed')",[partial,otherRoom]);await q("insert into meetings(user_id,room_id,title,date,start_time,end_time,status)values($1,$2,'Adjacent','2026-10-05','11:00','12:00','confirmed')",[partial,room]);await expectFail(()=>q("insert into meetings(user_id,room_id,title,date,start_time,end_time,status)values($1,$2,'Overlap','2026-10-05','10:30','11:30','confirmed')",[partial,room]),/مشغولة/);});
 await test('Confirmed booking owner and proposed fields are protected',async()=>{await as(user);await expectFail(()=>q("update meetings set status='modification_requested',start_time='09:30',pending_changes='{\"start_time\":\"09:30\"}'where id=$1",[booking]),/المقترحة/);await q("update meetings set status='modification_requested',pending_changes='{\"start_time\":\"09:30\"}'where id=$1",[booking]);await as(admin);await expectFail(()=>q('update meetings set user_id=$1 where id=$2',[admin,booking]),/ملكية/);});
 await test('Modification creates durable approver notification',async()=>{await as(partial);const count=await value("select count(*)::int from citl_notifications where entity_id=$1",[booking]);assert.ok(count>=1);});
 let actionId;
 await test('Effective schedule applies relocation and cancellation without publishing reasons',async()=>{await as(admin);await q("insert into academic_schedule(id,instructor,course_name,room_name,day_of_week,time_slot)values('s1','Teacher A','Course A','H 104','Tuesday','08:30')");const out=await value("select citl_secure_api('schedule_action.save',$1)",[JSON.stringify({data:{schedule_id:'s1',action_date:'2026-09-08',action_type:'move_room',replacement_room:'H 108',reason:'Private reason'}})]);actionId=out.data.id;const rows=await value("select citl_effective_schedule('2026-09-08')");assert.equal(rows[0].room_name,'H 108');assert.equal(rows[0].original_room,'H 104');assert.ok(!JSON.stringify(rows).includes('Private reason'));await q("update academic_schedule set cancelled_dates=array['2026-09-08']where id='s1'");assert.equal((await value("select citl_effective_schedule('2026-09-08')"))[0].status,'cancelled');});
 await test('Room and instructor overlapping edits rejected without cancelling another class',async()=>{await as(admin);await expectFail(()=>q("insert into academic_schedule(id,instructor,course_name,room_name,day_of_week,time_slot)values('s2','Teacher B','Course B','H104','Tuesday','09:00 - 10:00')"),/تعارض/);assert.equal(await value("select status from academic_schedule where id='s1'"),'active');});
 await test('Atomic setting merge preserves exam fields',async()=>{await as(admin);await q("select citl_patch_setting('tv_display_config','{\"examsEnabled\":false,\"examSlideDurationSeconds\":25}')");await q("select citl_patch_setting('tv_display_config','{\"slideDurationSeconds\":10}')");const v=await value("select setting_value from site_settings where setting_key='tv_display_config'");assert.equal(v.examsEnabled,false);assert.equal(v.examSlideDurationSeconds,25);});
 await test('Unverified profile changes reject; verified email link persists',async()=>{await as(user);await expectFail(()=>q("update profiles set linked_instructors=array['Teacher A']where id=$1",[user]));await expectFail(()=>q("select citl_link_instructors(array['Teacher A'])"));await as(admin);await q("insert into faculty_directory(full_name,email)values('Teacher A','User@example.invalid')");await as(user);const p=await value("select citl_link_instructors(array['Teacher A'])");assert.deepEqual(p.linked_instructors,['Teacher A']);});
 await test('Atomic report captures original action snapshot and rollback on missing item',async()=>{await as(admin);const out=await value('select citl_report_create($1,$2)',[JSON.stringify({output_mode:'print_or_pdf'}),[String(actionId)]]);assert.ok(out.ok);assert.equal(await value('select count(*)::int from schedule_report_batch_items where batch_id=$1',[out.id]),1);const before=await value('select count(*)::int from schedule_report_batches');await expectFail(()=>q("select citl_report_create('{}',array['missing'])"));assert.equal(await value('select count(*)::int from schedule_report_batches'),before);});
 await test('Ordinary registration cannot claim an unapproved academic identity',async()=>{await as(null);await q("insert into access_codes(code,code_hash,account_type)values('TEST',encode(digest('TEST','sha256'),'hex'),'faculty')");await as(user);await expectFail(()=>q('select citl_prepare_registration($1,$2)',['TEST',JSON.stringify({full_name:'Impostor',email:'other@example.invalid',linked_instructor:'Teacher A'})]));});
 await test('Head access is read-only and scoped',async()=>{await as(admin);await q("select citl_secure_api('head.save',$1)",[JSON.stringify({data:{department_key:'D1',profile_id:head}})]);await as(head);const out=await value("select citl_secure_api('management.snapshot')");assert.equal(out.read_only,true);assert.deepEqual(out.profiles,[]);await expectFail(()=>q("select citl_secure_api('term.save','{}')"));});
 await test('Dashboard attendance statistics RPC executes',async()=>{await as(admin);const v=await value('select citl_attendance_counts()');assert.equal(typeof v.pending,'number');});
 await test('Last full administrator cannot be demoted when partial managers remain',async()=>{await as(admin);await expectFail(()=>q("update profiles set role='user'where id=$1",[admin]),/آخر مدير/);});
 let term,token,scanId;
 await test('Create term and visitor, generate room QR with correct response shape',async()=>{await as(admin);const t=await value("select citl_secure_api('term.save',jsonb_build_object('data',jsonb_build_object('code','TEST-LIVE','name','Live test','starts_on',current_date-1,'ends_on',current_date+1,'is_active',true)))");term=t.data.id;await value("select citl_secure_api('visitor.save',$1)",[JSON.stringify({data:{term_id:term,full_name:'Visitor',profile_id:visitor,department_key:'D1'}})]);await q("insert into academic_schedule(id,instructor,course_name,room_name,day_of_week,time_slot)select 'live1','Visitor','Original scan course','SCAN 901',citl_day(timezone('Africa/Cairo',now())::date),to_char(timezone('Africa/Cairo',now())-interval '10 minutes','HH12:MI AM')||' - '||to_char(timezone('Africa/Cairo',now())+interval '25 minutes','HH12:MI AM')");const qr=await value("select citl_generate_room_qr($1,'SCAN 901')",[term]);assert.equal(qr.ok,true);assert.equal(qr.generated.room_name,'SCAN 901');token=qr.generated.token;assert.ok(token);});
 await test('QR scan records attendance and retry does not duplicate',async()=>{await as(visitor);const scan=await value('select citl_attendance_scan($1)',[token]);assert.equal(scan.ok,true,scan.error);assert.equal(scan.scan.course_name,'Original scan course');assert.equal((await value('select citl_attendance_scan($1)',[token])).already_recorded,true);await as(admin);assert.equal(await value("select count(*)::int from attendance_scans where lecturer_profile_id=$1",[visitor]),1);scanId=await value('select id from attendance_scans where lecturer_profile_id=$1',[visitor]);});
 await test('Historical attendance survives course edits with original snapshot',async()=>{await as(admin);await q("update academic_schedule set course_name='Renamed course'where id='live1'");assert.equal(await value("select session_snapshot->>'course_name'from attendance_scans where id=$1",[scanId]),'Original scan course');await expectFail(()=>q("delete from visiting_lecture_sessions where schedule_id='live1'"));});
 await test('Rotation invalidates old QR and rejected scan is audited',async()=>{await as(admin);const qr=await value("select citl_generate_room_qr($1,'SCAN 901')",[term]);await as(visitor);assert.equal((await value('select citl_attendance_scan($1)',[token])).ok,false);token=qr.generated.token;assert.equal((await value('select citl_attendance_scan($1)',[token])).ok,true);await as(admin);assert.ok(await value("select count(*)::int from security_audit_log where action='scan_rejected'and actor_id=$1",[visitor]));});
 await test('Cancellation prevents scanning even with a valid token',async()=>{await as(admin);await q("update academic_schedule set cancelled_dates=array[timezone('Africa/Cairo',now())::date::text]where id='live1'");await as(visitor);const out=await value('select citl_attendance_scan($1)',[token]);assert.equal(out.ok,false);await as(admin);await q("update academic_schedule set cancelled_dates='{}'where id='live1'");});
 await test('Presence heartbeat recovers a missing or ended session',async()=>{await as(visitor);const p=await value("select citl_presence_track('heartbeat','missing','/schedules/')");assert.ok(p.session_id);await value("select citl_presence_track('logout',$1,'/schedules/')",[p.session_id]);const next=await value("select citl_presence_track('heartbeat',$1,'/schedules/')",[p.session_id]);assert.ok(next.session_id);assert.notEqual(next.session_id,p.session_id);});
 await test('Ongoing lecture wins over overlapping QR grace window of next lecture',async()=>{await as(admin);await q("insert into academic_schedule(id,instructor,course_name,room_name,day_of_week,time_slot)select 'live2','Visitor','Next course','SCAN 902',citl_day(timezone('Africa/Cairo',now())::date),to_char(timezone('Africa/Cairo',now())+interval '25 minutes','HH12:MI AM')||' - '||to_char(timezone('Africa/Cairo',now())+interval '75 minutes','HH12:MI AM')");await as(visitor);const out=await value('select citl_attendance_scan($1)',[token]);assert.equal(out.ok,true,out.error);assert.equal(out.already_recorded,true);});
 await test('Visitor replacing a permanent instructor can scan the effective lecture',async()=>{await as(admin);await q("update academic_schedule set instructor='Permanent instructor'where id='live1'");await value("select citl_secure_api('schedule_action.save',jsonb_build_object('data',jsonb_build_object('schedule_id','live1','action_date',timezone('Africa/Cairo',now())::date,'action_type','replace','replacement_instructor','Visitor','reason','Approved test replacement')))");await as(visitor);const out=await value('select citl_attendance_scan($1)',[token]);assert.equal(out.ok,true,out.error);assert.equal(out.already_recorded,true);});
 await test('Pending requests cannot acquire reservation status without approval',async()=>{await as(user);const id=await value("insert into meetings(user_id,room_id,title,date,start_time,end_time,status)values($1,$2,'Pending workflow','2026-11-05','08:00','09:00','pending')returning id",[user,room]);await expectFail(()=>q("update meetings set status='modification_requested',pending_changes='{\"title\":\"Other\"}'where id=$1",[id]));await expectFail(()=>q("update meetings set status='cancellation_requested'where id=$1",[id]));await q("update meetings set title='Revised pending',status='pending'where id=$1",[id]);assert.equal(await value('select status from meetings where id=$1',[id]),'pending');await q('delete from meetings where id=$1',[id]);assert.equal(await value('select count(*)::int from meetings where id=$1',[id]),0);});
}catch(e){console.error('SETUP FAILURE',e.message,e.where);process.exitCode=1;}
finally{fs.writeFileSync('tests/results/database.json',JSON.stringify(results,null,2));await db.close();if(results.some(x=>!x.passed))process.exitCode=1;}
