const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const rt=require('../citl-runtime.js');
(async()=>{
 assert.equal(rt.date(new Date('2026-09-07T22:30:00Z')),'2026-09-08');
 assert.equal(rt.day(new Date('2026-09-07T22:30:00Z')),'Tuesday');
 assert.deepEqual(rt.slot('٠٢:٣٠ - ٠٤:٢٠'),{start:870,end:980});
 assert.deepEqual(rt.slot('02:30 AM - 03:00 AM'),{start:150,end:180});
 assert.equal(rt.slot('23:00'),null);
 assert.equal(rt.overlap(rt.slot('08:30 - 09:30'),rt.slot('09:30 - 10:00')),false);
 assert.equal(rt.room(' H ٠٠٢ LAP '),rt.room('h002 lab'));
 assert.equal(rt.can({role:'manager',permissions:{can_approve:true}},'can_approve'),true);
 assert.equal(rt.can({role:'manager',permissions:{can_approve:true}},'full'),false);
 assert.equal(rt.escape('<b>"&'), '&lt;b&gt;&quot;&amp;');
 const rows=Array.from({length:1203},(_,id)=>({id}));
 const loaded=await rt.all(()=>({range:(start,end)=>Promise.resolve({data:rows.slice(start,Math.min(end+1,start+100)),error:null})}));
 assert.equal(loaded.length,1203);assert.equal(loaded[1202].id,1202);
 await assert.rejects(()=>rt.all(()=>({range:()=>Promise.resolve({error:Error('Disconnected')})})),/Disconnected/);
 const events={};let cached=false;
 const context={URL,Response,self:{location:{origin:'https://test.invalid'},addEventListener:(name,fn)=>events[name]=fn},caches:{open:async()=>({put:async()=>{cached=true;throw Error('Quota');}})},fetch:async()=>new Response('fresh',{status:200})};
 vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../sw.js'),'utf8'),context);
 let response;events.fetch({request:{method:'GET',url:'https://test.invalid/tv_display/'},respondWith:p=>response=p});
 assert.equal(await(await response).text(),'fresh');assert.equal(cached,true);
 response=undefined;events.fetch({request:{method:'GET',url:'https://test.invalid/dashboard/'},respondWith:p=>response=p});assert.equal(response,undefined);
 console.log('PASS runtime: Cairo rollover, time slots, room aliases, permissions, escaping, capped pagination, failures and public-only SW caching.');
})().catch(e=>{console.error(e);process.exitCode=1});
