/* Isolated browser regression and visual evidence. Never contacts production. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),vm=require('node:vm');
const {chromium}=require('./node_modules/playwright'),jsQR=require('./node_modules/jsqr');
const root=path.resolve(__dirname,'..'),out=path.join(__dirname,'results','schedule-separated');fs.mkdirSync(out,{recursive:true});
const existing=fs.readFileSync(path.join(__dirname,'browser.cjs'),'utf8');
const stub=vm.runInNewContext(existing.slice(existing.indexOf('const stub=')+11,existing.indexOf('\n(async()=>')) .replace(/;\s*$/,''));
const fixture=`
window.__data.academic_schedule=Array.from({length:5},(_,i)=>({id:String(i),course_name:['إدارة سلاسل الإمداد','اقتصاديات النقل الدولي','النقل البحري وإدارة الموانئ','إدارة العمليات اللوجستية','التجارة الدولية'][i],course_code:'CITL'+(101+i),instructor:'د. محاضر تجريبي',room_name:i%2?'H 108':'H 104',day_of_week:'Monday',time_slot:['08:30 - 10:20','10:30 - 12:20','12:30 - 14:20','14:30 - 16:20','16:30 - 18:20'][i],status:i===3?'cancelled':'active',period_order:i+1}));
window.__data.exam_schedule=Array.from({length:14},(_,i)=>({id:i+1,exam_date:'2026-09-07',start_time:i<7?'09:00:00':'12:00:00',end_time:i<7?'11:00:00':'14:00:00',academic_level:i%4+1,course_name:['إدارة سلاسل الإمداد الدولية','الاقتصاد وإدارة الخدمات اللوجستية','النقل الدولي والتجارة الخارجية'][i%3],course_code:'CITL'+(200+i),instructor:'د. محاضر امتحان تجريبي',room_name:'H '+(104+i%4),course_language:i%2?'E':'A',group_number:1}));
window.__data.site_settings[0].setting_value.activeRooms=['H 104','H 108'];
`;
(async()=>{
 const checks=[];let server,browser;
 try{
  for(const file of ['today/index.html','study/index.html','tv_display/index.html']){const html=fs.readFileSync(path.join(root,file),'utf8');for(const m of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi))if(!m[1].includes('src='))new vm.Script(m[2],{filename:file});}
  for(const file of ['schedule-common.js','schedule-portal.js','tv-schedule.js'])new vm.Script(fs.readFileSync(path.join(root,'assets',file),'utf8'),{filename:file});
  server=http.createServer((req,res)=>{let p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{if(fs.statSync(p).isDirectory())p=path.join(p,'index.html');res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png'})[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(p));}catch{res.writeHead(404).end();}}).listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));const base='http://127.0.0.1:'+server.address().port;
  browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1050},timezoneId:'Africa/Cairo',serviceWorkers:'block'});
  await context.route('**/*',route=>{const url=route.request().url();if(url.includes('/vendor/supabase-js'))return route.fulfill({contentType:'application/javascript',body:stub+fixture});if(!url.startsWith(base))return route.abort();return route.continue();});
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.setFixedTime(new Date('2026-09-07T06:00:00Z'));
  async function ready(){await page.waitForFunction(()=>!document.getElementById('refresh').disabled);}
  for(const [route,heading,count,kind] of [['/today/','جداول الامتحانات',14,'exams'],['/study/','الجداول الدراسية',5,'academic']]){
   await page.goto(base+route);await ready();assert.equal(await page.locator('.schedule-card').count(),count);assert.equal(await page.locator('h1').innerText(),heading);
   assert.equal(await page.locator('[role=tab],dialog,canvas,#share,[id*=qr],script[src*=qrcode]').count(),0);
   const calls=await page.evaluate(()=>window.__calls);assert.equal(calls.some(c=>kind==='academic'?c.table==='exam_schedule':c.rpc==='citl_effective_schedule'),false);
   const channels=await page.evaluate(()=>window.__channels.map(c=>c.filter.table));assert.deepEqual(channels,kind==='academic'?['academic_schedule','schedule_actions']:['exam_schedule']);
   checks.push(route+' is independent, reads/subscribes only to its data, with no tabs, sharing or QR tools');
   await page.screenshot({path:path.join(out,kind+'-desktop.png'),fullPage:true});
   for(const width of [390,320]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);if(width===390)await page.screenshot({path:path.join(out,kind+'-mobile.png'),fullPage:true});}
   await page.setViewportSize({width:1440,height:1050});
  }
  checks.push('Both independent pages fit 320px and 390px mobile widths');
  await page.locator('#search').fill('سلاسل');assert.equal(await page.locator('.schedule-card').count(),1);await page.locator('#search').fill('');await page.locator('#room-filter').selectOption('H 108');await page.locator('#status-filter').selectOption('cancelled');assert.equal(await page.locator('.schedule-card').count(),1);
  const bookmark=page.url();assert.equal(new URL(bookmark).pathname,'/study/');assert.equal(new URL(bookmark).searchParams.has('view'),false);assert.equal(new URL(bookmark).searchParams.has('date'),false);await page.goto(bookmark);await ready();assert.equal(await page.locator('.schedule-card').count(),1);checks.push('Bookmarks retain academic route and filters while following today');
  await page.locator('#room-filter').selectOption('');await page.locator('#status-filter').selectOption('');
  await page.evaluate(()=>window.__failed=true);await page.locator('#refresh').click();await ready();assert.equal(await page.locator('.schedule-card').count(),5);assert.equal(await page.locator('#data-notice').isVisible(),true);
  await page.locator('#schedule-date').fill('2026-09-09');await page.locator('#schedule-date').dispatchEvent('change');await ready();assert.equal(await page.locator('.schedule-card').count(),0);checks.push('Refresh failures retain same-date data only with a visible warning');
  await page.evaluate(()=>window.__failed=false);await page.locator('#go-today').click();await ready();await page.emulateMedia({media:'print'});assert.equal(await page.locator('.filters').isVisible(),false);assert.equal(await page.locator('.actions').isVisible(),false);await page.pdf({path:path.join(out,'academic-print.pdf'),format:'A4',printBackground:true});await page.emulateMedia({media:'screen'});checks.push('Schedule printing still works without QR or sharing');
  await page.goto(base+'/today/');await ready();await page.evaluate(()=>window.__data.exam_schedule=[]);await page.locator('#refresh').click();await ready();assert.equal(await page.locator('.schedule-card').count(),0);assert.match(await page.locator('#results').innerText(),/لا توجد الامتحانات/);assert.equal(await page.locator('h1').innerText(),'جداول الامتحانات');assert.equal(await page.evaluate(()=>window.__calls.some(c=>c.rpc==='citl_effective_schedule')),false);checks.push('Empty exams page never switches itself to academic schedules');
  await page.setViewportSize({width:1920,height:1080});await page.goto(base+'/tv_display/');await page.locator('.exam-entry').first().waitFor();
  async function decodedTV(expected){await page.waitForFunction(expected=>{const a=document.getElementById('tv-portal-link'),i=document.getElementById('tv-portal-qr');return !a.hidden&&a.getAttribute('href')===expected&&i.complete&&i.naturalWidth>0;},expected);const raw=await page.locator('#tv-portal-qr').evaluate(img=>{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);return{pixels:Array.from(ctx.getImageData(0,0,c.width,c.height).data),width:c.width,height:c.height}});assert.equal(jsQR(Uint8ClampedArray.from(raw.pixels),raw.width,raw.height).data,expected);}
  await decodedTV(base+'/today/');assert.equal(await page.evaluate(()=>examPages.reduce((n,p)=>n+p.items.filter(x=>!x.isDivider).length,0)),14);checks.push('Exam slide QR independently decodes to the exams-only page');
  // Turn off exams through the same remote setting the dashboard uses, with exam data still present.
  await page.evaluate(async()=>{window.__data.site_settings[0].setting_value.examsEnabled=false;window.__data.site_settings.push({setting_key:'tv_poster_config',setting_value:{enabled:true}});window.__data.tv_posters=[{id:'poster-1',title:'إعلان تجريبي',image_url:location.origin+'/CITL_Banner.png',fit_mode:'contain',is_active:true,display_order:1,duration:20}];await fetchData();clearInterval(progressInterval);});
  assert.equal(await page.evaluate(()=>isExamMode),false);assert.equal(await page.evaluate(()=>window.__data.exam_schedule.length),14);assert.equal(await page.evaluate(()=>tvPosters.length),1);await decodedTV(base+'/study/');checks.push('Disabling exams keeps academic slides plus posters and changes QR despite remaining exam records');
  await page.evaluate(()=>renderMasterSlide(displayRooms.length));await page.locator('.tv-poster-card').waitFor();assert.equal(await page.locator('#tv-portal-link').isVisible(),false);await page.waitForFunction(()=>document.getElementById('main-header-title').textContent.includes('الإعلانات'));await page.screenshot({path:path.join(out,'tv-poster.png'),animations:'disabled'});checks.push('Advertisement slide hides the schedule QR');
  await page.evaluate(()=>renderMasterSlide(0));await decodedTV(base+'/study/');checks.push('Returning to academic slide restores the academic QR');
  await page.waitForFunction(()=>document.getElementById('main-header-title').textContent.includes('الدراسية'));await page.screenshot({path:path.join(out,'tv-academic.png'),animations:'disabled'});
  await page.evaluate(async()=>{window.__data.site_settings[0].setting_value.examsEnabled=true;await fetchData();clearInterval(progressInterval);});await decodedTV(base+'/today/');assert.equal(await page.evaluate(()=>isExamMode),true);checks.push('Re-enabling exams restores the exam slide and exam QR');
  // A late QR generation must never reappear on a poster.
  await page.evaluate(async()=>{const pending=CITLDisplay.showScheduleQR('academic');CITLDisplay.showScheduleQR(null);await pending;});assert.equal(await page.locator('#tv-portal-link').isVisible(),false);checks.push('Asynchronous QR updates cannot leak onto advertisement slides');
  assert.deepEqual(errors,[]);checks.push('No uncaught JavaScript errors');fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({passed:true,network:'All external requests blocked; local synthetic data only',checks},null,2));console.log(JSON.stringify({passed:true,checks},null,2));
 }finally{if(browser)await browser.close();if(server)server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
